### PR TITLE
Do not return a decrypt error return code but KRB5KDC_ERR_PREAUTH_FAILED

### PR DESCRIPTION
**Pull request by gladiac**
This makes it consistent with other Kerberos implementations.

### CODE REVIEW

**Comment by gladiac** [comment]
Fixed, I'm checking for both return codes now. It is possible that a new kinit is used against an older KDC.

**Comment by greghudson** [comment]
Hm, I'm not sure that's correct either.  If you're using PKINIT and it doesn't work, for example, you might not even have entered a password.  I'll make a note to discuss this next Tuesday.

**Comment by greghudson** [comment]
From today's discussion:

* We could treat the kinit behavior separately from this change (although the test suite needs to know what message to expect from kinit), since KDCs and clients are independent and non-MIT KDCs already have the new behavior.  But I would like to have a plan for dealing with the problem in kinit before changing the KDC behavior.

* kinit could use its own prompter function and make note of whether it was prompted for a password, and translate KRB5_PREAUTH_FAILED to "Password incorrect" only if there was a password prompt.  I will look into this when time permits.

**Comment by greghudson** [comment]
I opened PR #491 to deal with the kinit reporting issue; please go ahead and narrow this commit back down to the KDC behavior change.

**Comment by gladiac** [comment]
Done ...

**Comment by greghudson** [comment]
Pushed to master as 2653d69e0705a925597dff10083a24a77e2a20af.

**Pull request closed without merging**
