### PR TITLE
Documentation Fixes

### PR DESCRIPTION
**Pull request by mmattioli**
Proposal
===

* Fixed a few typos in various places throughout the documentation.
* Updated the copyright year in the top-level `README` to 2015.
* Removed unnecessary header underline characters from file in documentation.

Reasoning
===

The typos and character removal are pretty straightforward. The copyright year should be adjusted to reflect the current year (2015).

### CODE REVIEW

**Comment by greghudson** [comment]
https://github.com/greghudson/krb5/commits/docfixes has what I plan to push, in three commits.  The first commit has the typo, whitespace, and formatting changes, except for the ones to doc/procedures.txt.  It is marked for pullup.  The second commit has the README copyright year update (how did we miss this in February).  The third commit removes doc/procedures.txt.

**Comment by mmattioli** [comment]
@greghudson I just pushed another commit (8a4d299) removing a reference to a file that no longer exists, check it out when you get the chance

**Comment by tlyu** [comment]
The release snapshot process dynamically generates doc/CHANGES; that file deliberately does not exist in the repository.

**Comment by mmattioli** [comment]
@tlyu thanks, just reverted

**Comment by tlyu** [comment]
@greghudson your commits look good.

**Comment by greghudson** [comment]
Pushed to master as 4ad099d28437b542b76053f44f18f763bdcd5152 6ef48708cf97d484f3dddafff970aa03a72824f2 531cbea82523ee82f3ad19028f36b4f88eaf7cdb

**Pull request closed without merging**
