### PR TITLE
Kfw updates

### PR DESCRIPTION
**Pull request by kaduk**
Some updates, partially as a result of testing beta1, and partially bugfixes for already-known bugs.

### CODE REVIEW

**Comment by greghudson** [comment]
Should that last commit have the summary "Make registry hostrealm module highest precedence"?

**Comment by kaduk** [comment]
Yes.  Clearly my morning tea hasn't taken effect yet...

**Comment by greghudson** [comment]
In the commit message for 448b6e0, "some user configuration allows for..." doesn't seem like correct English.

I've finished reviewing everything and didn't find any other problems.

**Comment by kaduk** [comment]
Pushed to master as d376d5948d2af7dcf60368bc3b6fe6c23172a831; 27e6ab7e5b6a0538f529f440aeb967822eff8f57 was not supposed to go in this pull request.

**Pull request closed without merging**
