### PR TITLE
SPNEGO: Add special case for NTLMSSP+MechListMIC

### PR DESCRIPTION
**Pull request by simo5**
This is an initial RFC PR, the code does work and operates as intented in a synthetic test performed using python-gssapi and the gss-ntlmssp mechanism, but hasn't been tested against a conformant implementation (Windows) yet.

### CODE REVIEW

**Comment by simo5** [comment]
This is the way I tested this so far:
create a file with some credentials:
```
$ echo F23:guest:guest > ~/ntlmcreds.txt
$ export NTLM_USER_FILE=~/ntlmcreds.txt
$ python
import gssapi

spnego = gssapi.raw.oids.OID.from_int_seq('1.3.6.1.5.5.2')
c = gssapi.creds.Credentials(mechs=[spnego], usage='initiate')
tname = gssapi.raw.names.import_name("F23/server", name_type=gssapi.raw.types.NameType.hostbased_service)
ac = gssapi.creds.Credentials(mechs=[spnego], usage='accept')

seci = gssapi.SecurityContext(creds=c, name=tname, mech=spnego, usage='initiate')
seca = gssapi.SecurityContext(creds=ac, usage='accept')
it = seci.step(token=None)
ot = seca.step(token=it)
it = seci.step(token=ot)
ot = seca.step(token=it)
it = seci.step(token=ot)

e = seci.wrap("Secrets", True)
o = seca.unwrap(e.message)

o.message
'Secrets'
```

So far I checked with GDB that the seq numbers were reset after the MEchListMIC operation happened and started again from 0.

**Comment by greghudson** [comment]
Please factor out the export/import/import into a helper to minimize the expansion of process_mic().

**Comment by simo5** [comment]
Ok moved context duplication in a separate helper function.

**Comment by greghudson** [comment]
I think this looks okay apart from trivial stuff like comments and style issues.  I'll await confirmation that this interoperates with Windows.

**Comment by greghudson** [comment]
It would be nice to trim down the call sites since there are two of them.  Moving the comment and the mechanism test into the helper function would be a start.  I don't know if there's much we can do about the error-handling parts.

**Comment by simo5** [comment]
Ok moved the ntlmssp oid check in the reset state function as well as the MS-SPNG related comment, which has been expanded to explain the behavior of the mechanism.
Once this was done I was able to call the function w/o having to duplicate the error handling.

HTH.

**Comment by greghudson** [comment]
Pushed to master as cb96ca52a3354e5a0ea52e12495ff375de54f9b7.

**Pull request closed without merging**
