### PR TITLE
fix core dump in get profile vaule

### PR DESCRIPTION
**Pull request by HelloCarry**

### CODE REVIEW

**Comment by HelloCarry** [comment]
I am doing test on krb5, when I repeatedly run the following command.
```
# testcase
kdb5_util create -s -P master
kdb5_util add_mkey -s << EOF
Testpasswd@123
Testpasswd@123
EOF
kdb5_util add_mkey -s << EOF
Testpasswd@123
Testpasswd@123
EOF
kdb5_util use_mkey 2 'now+2days'
kdb5_util list_mkeys
kdb5_util stash
kdb5_util purge_mkeys -f
kdb5_util dump
kdb5_util dump dumpfile
kdb5_util dump dumpfile1 kadmin/changepw@KRBTEST.COM
kdb5_util dump -verbose dumpfile2 kadmin/changepw@KRBTEST.COM kadmin/admin@KRBTEST.COM
kdb5_util tabdump -o keyinfo.txt keyinfo
kdb5_util load -update dumpfile
kdb5_util destroy -f
```
A core dump occurs in the system. According to the core dump, the exception point is caused by the null pointer of cp in the static void end_list(struct profile_string_list *list, char ***ret_list) function.
```
# testcase
kdb5_util create -s -P master
kdb5_util add_mkey -s << EOF
Testpasswd@123
Testpasswd@123
EOF
kdb5_util add_mkey -s << EOF
Testpasswd@123
Testpasswd@123
EOF
kdb5_util use_mkey 2 'now+2days'
kdb5_util list_mkeys
kdb5_util stash
kdb5_util purge_mkeys -f
kdb5_util dump
kdb5_util dump dumpfile
kdb5_util dump dumpfile1 kadmin/changepw@KRBTEST.COM
kdb5_util dump -verbose dumpfile2 kadmin/changepw@KRBTEST.COM kadmin/admin@KRBTEST.COM
kdb5_util tabdump -o keyinfo.txt keyinfo
kdb5_util load -update dumpfile
kdb5_util destroy -f
```
Therefore, the protection for the scenario where `list->list` is 0 is added in the PR. Otherwise, `*cp` may cause panic.

**Comment by HelloCarry** [comment]
@greghudson

**Comment by greghudson** [comment]
Can you give the full stack trace?

**Comment by HelloCarry** [comment]
> Can you give the full stack trace?

Hi @greghudson ,I copy the stack trace in the first message.

**Comment by greghudson** [comment]
Thanks.

I suggest the alternative fix of changing the for loop to `for (cp = list->list; cp && *cp; cp++)`.

**Comment by HelloCarry** [comment]
> 
Hi @greghudson 
I have alternative fix of changing the for loop to for `(cp = list->list; cp && *cp; cp++)`

**Comment by HelloCarry** [comment]
Hi @greghudson 
 Could you please review this PR again? If there is no problem, I hope this PR can be merged.

**Pull request merged**
