### PR TITLE
update copyright years to 2016

### PR DESCRIPTION
**Pull request by mmattioli**
Updated copyright years to 2016 where appropriate

### CODE REVIEW

**Comment by SaharahSarah** [comment]
Someone is being proactive!

**Comment by mmattioli** [comment]
:grin: Happy new year, @SaharahSarah! :tada:

**Comment by SaharahSarah** [comment]
Happy new year @mmattioli !!! 😁🎇🎆🎉🎊

**Comment by tlyu** [comment]
In this patch, I'm not sure I understand the criteria used to determine which files needed their copyright years updated. We usually don't update copyright years on source code unless there is a copyrightable change made in that year. The changes that apply to things like project-wide documentation seem reasonable.

**Comment by greghudson** [comment]
I agree with Tom.  My best non-lawyer understanding is that mechanically updating copyright years on files isn't really honest if you haven't changed the file.  Projects still sometimes do it, of course, and it's relatively harmless due to the extremely long term of copyright protection, but we haven't made a practice of it.

**Comment by mmattioli** [comment]
@greghudson @tlyu I've updated with a different set of changed files

**Comment by greghudson** [comment]
Pushed to master as 6614a8859d3fa539c3eda23ad5fad066375278c4

**Pull request closed without merging**
