### PR TITLE
Renaming reconf script to align more closely with autotools conventions

### PR DESCRIPTION
**Pull request by SaharahSarah**
There are certain conventions users expect when working with a project
that uses autotools. Deviating from those conventions adds confusion and
complexity to a project, and let's face it, krb5 is not exactly a
shining example of a convention-conforming project. In an effort to try
to simplify the krb5 build, I am moving and renaming the src/util/reconf
script to src/bootstrap. The bootstrap name was chosen since the
autotools documentation says it is the preferred name. For more
information on this please see:

https://goo.gl/JRvpYK
https://goo.gl/V1i521

ticket: 8299

### CODE REVIEW

**Comment by SaharahSarah** [comment]
Did you hear that? That's the sound of build script maintainers all groaning at once. I'm sure we'll hear that much more in the coming months.

**Comment by greghudson** [comment]
At a minimum, the documentation should be updated.  We should probably discuss this on Tuesday.

**Comment by SaharahSarah** [comment]
I updated all references to the old script.

**Comment by SaharahSarah** [comment]
Let's wait on this. There seems to be a lot of opinion on it, and we might be leaning towards just deleting the script completely.

**Comment by tlyu** [comment]
Closing because I just opened PR #374 as an alternative.

**Pull request closed without merging**
