### PR TITLE
Use the appropriate nm via the exported variable to help/fix cross compiling

### PR DESCRIPTION
**Pull request by tgurr**
Reason explained here: https://galileo.mailstation.de/gerrit/#/c/1117/
Idea for the fix taken from: http://opensource.apple.com/source/llvmgcc42/llvmgcc42-2336.9/libstdc++-v3/scripts/make_exports.pl

### CODE REVIEW

**Comment by tgurr** [comment]
Is there anything wrong with my commit? For clarification this is needed when the build tools are prefixed like for example we do to allow to cross compile:

"Some build tools are now prefixed with the host architecture, so you can call the one you want to build for, for example you'll find /usr/${host}/bin/${host}-nm and possibly multiple /usr/${host}/bin/${target}-nm"

The only problem within krb5 is the single hardcoded nm in the src/util/export-check.pl file, for everything else autotools are doing the right thing.

**Comment by tlyu** [comment]
I think I recall us being confused as to why you could expect the NM variable to be exported.  As far as I know we currently do nothing to export the NM make variable as an environment variable.

**Comment by tgurr** [comment]
It falls back to nm when nothing is exported so existing working behaviour isn't affected. However I'm not that firm in Perl so if you come up with a better fix you're more happy with then even better.

Another approach would be to sed in our prefixed nm in our package build script downstream, but I'd rather like to see this fixed properly upstream since I'm sure more and more distributions and/or projects will run into such issues in the future and there are plenty of such problems, so we try our best to upstream our fixes so everyone can benefit.

**Comment by tlyu** [comment]
Do you explicitly set the NM environment variable in your downstream build process?  It seems like we don't even set a make variable for it, so we would have to introduce some additional autoconf tests if we wanted to set the make variable "correctly".  Prefixing the command as in "NM=$(NM) .../export-check.pl" could then work.

You might be able to skip the export-check.pl invocation if you're not adding/removing APIs or making any changes to the export list; it's mostly there as a consistency check.

**Comment by greghudson** [comment]
I think I would prefer to conditionalize running export-check on --enable-maintainer-mode, which Tom was starting to get at in his last sentence.  That requires a little bit of restructuring of the shlib.conf outputs, I think.

**Comment by tgurr** [comment]
Yes, we set e.g. NM=x86_64-pc-linux-gnu-nm in our build environment.

Putting the export-check into --enable-maintainer-mode would probably also work for us downstream since we usually don't enable maintainer-mode when building packages.

**Comment by tlyu** [comment]
Closing because I've opened PR #373 with an alternative solution.

**Pull request closed without merging**
