### PR TITLE
Allow cross-realm RBCD with PAC not the only ad element

### PR DESCRIPTION
**Pull request by iboukris**
Follow-up to #1013

### CODE REVIEW

**Comment by iboukris** [comment]
Pushed a new fixup, sorry for all the back and forth on this.

**Comment by iboukris** [comment]
And another update, we shouldn't try to verify singed-path on cross-realm tickets, squashed now.

**Comment by iboukris** [comment]
One more, it wouldn't harm to check for the PAC in cross-realm tickets (at least for the time being).

**Comment by greghudson** [comment]
Pushed changes mostly just to the commit messages; the only code change I made was to check the cross-realm flag before calling has_pac() to more efficiently process within-realm requests.  This should be ready to merge.

**Comment by iboukris** [comment]
Looks good, thanks.

**Pull request merged**
