### PR TITLE
fuzzing: oss-fuzz init

### PR DESCRIPTION
**Pull request by pkillarjun**
I'm rewriting everything from scratch; I need your basic review on:

1) Documentation Update `doc/build/options2configure.rst`.
2) Variable Naming in Build System.
3) License of .C Files.
4) Should I use .zip files (some people do not prefer this due to security reasons) or folders (this will make the management messy and hard)?
5) And a simple question: "How these `deps` files are created? I'm unable to figure this out."

### CODE REVIEW

**Comment by greghudson** [comment]
deps files are generated with `make depend`; the build directory must be separate from the source directory for it to work.  I can review the build materials to make sure the appropriate variables are set.

What is the advantage of zip files over folders for the corpus materials?  I don't really want to be putting zip files under version control.

**Comment by pkillarjun** [comment]
> deps files are generated with make depend; the build directory must be separate from the source directory for it to work. I can review the build materials to make sure the appropriate variables are set.

Thank you this was very helpful.

>What is the advantage of zip files over folders for the corpus materials? I don't really want to be putting zip files under version control.

There are none, but .zip files are easier to control than corpus files, which are around 50+. So, there is that.
Give me one more week; there are still some bottlenecks to be fixed.

**Comment by pkillarjun** [comment]
ping @greghudson 

My work is done for this PR. Can you review it?

* I will add more fuzz tests after the merge. Adding them here cab be overwhelming;

#### oss-fuzz Work:
* 1) Merge this PR;
* 2) Update `oss-fuzz` Repo https://github.com/google/oss-fuzz/tree/master/projects/krb5, Like this [brpc](https://github.com/google/oss-fuzz/pull/11531/files)
* 3) Add a CIFuzz workflow to the krb5 project.
* 4) Add New fuzz test.

**Comment by pkillarjun** [comment]
## Comment before the question (FQA).

#### Why use `$(CXX_LINK)`  [for example](https://github.com/krb5/krb5/pull/1346/files#diff-aea51f2cc62b114ddb20ad1fe891e182908dd5eb919983e4601ff058e1d8b7bfR36) ?

`$(FUZZ_LDFLAGS)` requires [clang++ as a linker](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#Requirements).

#### What is the use for [`oss-fuzz.sh`](https://github.com/krb5/krb5/pull/1346/files#diff-b93bd9a0b0985409d7e9222b2a8102be7a84ae5a2feb292fd3cb688f88a63b3f)?

This will be used as `build.sh` for OSS-Fuzz infrastructure.
I'm copying the design from [Ethereum](https://github.com/ethereum/go-ethereum/blob/master/oss-fuzz.sh); it's pretty cool.

#### Where is the error handling?

I've only done error handling for those that are important and their failures can create noise. Also, I don't want to bloat the fuzz target.

**Comment by greghudson** [comment]
I made some nitpicky changes.  Addtional notes:

* For copyright statements on the new files, our historical practice would be to put your name (or your organization's name if you're doing work for hire) in the copyright notice, and then we add the copyright and license statement to doc/notice.rst and regenerate NOTICE.

* I'm slightly worried about the fuzz targets that reach into other build directories for internal object or header files.  When a regular test wants to do this, we normally position it within the same directory as the library or program.  That would obviously be in conflict with the strategy of putting the fuzzing targets in one directory and conditionalizing that directory's build.  I'm not requesting any changes at the moment, but I will think about the issue further.

* I don't think we need `$(ALL_CFLAGS)` when using `$(CXX_LINK)`.  `$(CXXFLAGS)` should already be included (see the definitions of CXX_LINK_SHARED in config/shlib.conf).

* In tests/fuzzing/README, would it be easier to recommend just building with `-g` and not `-O1`?  Then we wouldn't need `-gline-tables-only` and `-fno-omit-frame-pointer`.  Also, `-DFUZZING_BUiLD_MODE_UNSAFE_FOR_PRODUCTION` doesn't do anything in our tree (unless you plan to do something similar; I know basically how it's used in OpenSSL).

**Comment by pkillarjun** [comment]
>I'm slightly worried about the fuzz targets that reach into other build directories for internal object or header files. When a regular test wants to do this, we normally position it within the same directory as the library or program. That would obviously be in conflict with the strategy of putting the fuzzing targets in one directory and conditionalizing that directory's build. I'm not requesting any changes at the moment, but I will think about the issue further.

I do agree with you, but I'm biased toward this approach because I see it a lot in the wild. The design you are talking about is used in Google's Fuchsia OS, but V8 uses this one.

Currently, everything is working fine, but in the future, there will be build breaks because of this. There are going to be missing header files and linker errors; one of the culprits is `NDROBJ`.

> Also, -DFUZZING_BUiLD_MODE_UNSAFE_FOR_PRODUCTION doesn't do anything in our tree (unless you plan to do something similar; I know basically how it's used in OpenSSL).

Leave It for Future.

**Comment by pkillarjun** [comment]
### Oss-Fuzz Test
```bash
git clone --depth=1 -b krb5-ideal https://github.com/pkillarjun/oss-fuzz.git
cd oss-fuzz/

python infra/helper.py build_image   krb5
python infra/helper.py build_fuzzers krb5 --engine libfuzzer --sanitizer address
python infra/helper.py check_build   krb5 --engine libfuzzer --sanitizer address
``` 

### ERROR
```log
python infra/helper.py build_fuzzers krb5 --engine libfuzzer --sanitizer address

....
make[2]: Entering directory '/src/krb5/src/tests/fuzzing'
clang -DHAVE_CONFIG_H  -I../../include -I../../include -I./../../lib/krb5/ccache -I./../../kdc -I./../../util/profile -DKRB5_DEPRECATED=1 -DKRB5_PRIVATE  -fcommon -O1 -fno-omit-frame-pointer -gline-tables-only -Wno-error=enum-constexpr-conversion -Wno-error=incompatible-function-pointer-types -Wno-error=int-conversion -Wno-error=deprecated-declarations -Wno-error=implicit-function-declaration -Wno-error=implicit-int -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -Werror=unknown-warning-option -Wall -Wcast-align -Wshadow -Wmissing-prototypes -Wno-format-zero-length -Woverflow -Wstrict-overflow -Wmissing-format-attribute -Wmissing-prototypes -Wreturn-type -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wunused-variable -Wunused-value -Wunknown-pragmas -Wsign-compare -Wnewline-eof -Werror=uninitialized -Werror=pointer-arith -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=implicit-int -Werror=declaration-after-statement -Werror-implicit-function-declaration -pthread  -c fuzz_chpw.c
fuzz_chpw.c:54:25: error: passing 'const uint8_t *' (aka 'const unsigned char *') to parameter of type 'void *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
   54 |     data_in = make_data(data, size);
      |                         ^~~~
../../include/k5-int.h:2234:17: note: passing argument to parameter 'data' here
 2234 | make_data(void *data, unsigned int len)
      |                 ^
1 error generated.
make[2]: *** [Makefile:469: fuzz_chpw.o] Error 1
make[2]: Leaving directory '/src/krb5/src/tests/fuzzing'
make[1]: *** [Makefile:1210: all-recurse] Error 1
make[1]: Leaving directory '/src/krb5/src/tests'
make: *** [Makefile:1522: all-recurse] Error 1
ERROR:__main__:Building fuzzers failed.
```

#### Fix using pointer casting.
```c
    data_in = make_data((void *)data, size);
```


### Run time bugs

* `fuzz_json`, `fuzz_util`.
The `malloc` function does not force the last byte to be `\0`, so using `data_in[size] = '\0';` after `memcpy`.

**Comment by pkillarjun** [comment]
My changes after your changes;
* https://github.com/krb5/krb5/compare/adb2fa38e5d7f0ff33244122883bab457696d8de..e62429c9854826ae969ded33fe520bac98b26875
* https://github.com/krb5/krb5/compare/e62429c9854826ae969ded33fe520bac98b26875..3d15ecbe8cfd3be2d62d7f6f1fd29d17fc50ab0b

**Comment by pkillarjun** [comment]
> I will undo the cast changes;

Already [done]( https://github.com/krb5/krb5/compare/e62429c9854826ae969ded33fe520bac98b26875..3d15ecbe8cfd3be2d62d7f6f1fd29d17fc50ab0b).

> we have the alternative options of using strndup() from POSIX.1-2008 or k5memdup0() from k5-int.h.

[This](https://github.com/krb5/krb5/pull/1346/commits/47f4f830aacaa05ad52378c003405acb8286961a) looks much clearer, thanks. I'm using `k5memdup0`.

**Comment by pkillarjun** [comment]
Note: the bug report that is generated on oss-fuzz is from this PR.

**Comment by greghudson** [comment]
I made just a few changes this time, hopefully not breaking anything.  Let me know if it passes tests on your side and I'll merge it.

**Comment by pkillarjun** [comment]
Everything is working fine on my side too. Also, I updated the seed corpus using [afl-cmin](https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/fuzzing_in_depth.md#b-making-the-input-corpus-unique) to add only unique test cases.

**Pull request merged**
