### PR TITLE
replaced_reply_key support

### PR DESCRIPTION
**Pull request by greghudson**
This PR contains deferred work from PR #1225 to communicate the AS reply key to issue_pac(), but only when the reply key was replaced (not strengthened) by a preauth mech such as PKINIT.  I haven't done proper commit messages or added a test, but there's enough here for @cryptomilk to test the Samba side of things.

### CODE REVIEW

**Comment by greghudson** [comment]
The way this is supposed to work is: pkinit_srv.c:verify_client_san() calls cb->match_client(), which is kdc_preauth.c:match_client().  This function calls krb5_db_get_principal() on the parsed certificate SAN, and then compares the canonical name of the result to the canonical name of the request client.

This should handle realm aliasing; can you determine where it's going wrong?

**Comment by cryptomilk** [comment]
I have the following kdc.conf:

```
[kdcdefaults]
    kdc_ports = 88
    kdc_tcp_ports = 88
    restrict_anonymous_to_tgt = true
[realms]
    ADDOM.SAMBA.EXAMPLE.COM = {
        master_key_type = aes256-cts
        default_principal_flags = +preauth
        pkinit_identity = FILE:/home/asn/workspace/projects/samba/asn-pkinit/st/ad_dc/private/tls/kdc.pem,/home/asn/workspace/projects/samba/asn-pkinit/st/ad_dc/private/tls/key.pem
        pkinit_anchors = FILE:/home/asn/workspace/projects/samba/asn-pkinit/st/ad_dc/private/tls/ca.pem
        pkinit_eku_checking = scLogin
        pkinit_indicator = pkinit
    }

    addom.samba.example.com = {
        master_key_type = aes256-cts
        default_principal_flags = +preauth
        pkinit_identity = FILE:/home/asn/workspace/projects/samba/asn-pkinit/st/ad_dc/private/tls/kdc.pem,/home/asn/workspace/projects/samba/asn-pkinit/st/ad_dc/private/tls/key.pem
        pkinit_anchors = FILE:/home/asn/workspace/projects/samba/asn-pkinit/st/ad_dc/private/tls/ca.pem
        pkinit_eku_checking = scLogin
        pkinit_indicator = pkinit
    }

    ADDOMAIN = {
        master_key_type = aes256-cts
        default_principal_flags = +preauth
        pkinit_identity = FILE:/home/asn/workspace/projects/samba/asn-pkinit/st/ad_dc/private/tls/kdc.pem,/home/asn/workspace/projects/samba/asn-pkinit/st/ad_dc/private/tls/key.pem
        pkinit_anchors = FILE:/home/asn/workspace/projects/samba/asn-pkinit/st/ad_dc/private/tls/ca.pem
        pkinit_eku_checking = scLogin
        pkinit_indicator = pkinit
    }

[dbmodules]
    db_module_dir = /home/asn/workspace/projects/samba/asn-pkinit/bin/shared

    ADDOM.SAMBA.EXAMPLE.COM = {
        db_library = samba
    }

    addom.samba.example.com = {
        db_library = samba
    }

    ADDOMAIN = {
        db_library = samba
    }

[logging]
    kdc = FILE:/home/asn/workspace/projects/samba/asn-pkinit/st/ad_dc/logs/mit_kdc.log
```

The log file is here:
[mit_kdc.log](https://github.com/krb5/krb5/files/7881260/mit_kdc.log)

The client used:
`kinit --request-pac -r 1h -X X509_user_identity=FILE:./st/ad_dc/pkinit/USER-pkinit@addom.samba.example.com-cert.pem,./st/ad_dc/pkinit/USER-pkinit@addom.samba.example.com-private-key.pem pkinit@ADDOM.SAMBA.EXAMPLE.COM`

```
X.509 Certificate Information:
    Version: 3
    Serial Number (hex): 05
    Issuer: EMAIL=ca-samba.example.com@samba.example.com,CN=CA of samba.example.com,OU=CA Administration,O=SambaSelfTesting,L=SambaCity,ST=SambaState,C=US
    Validity:
        Not Before: Fri Jun 03 19:30:47 UTC 2016
        Not After: Thu May 29 19:30:47 UTC 2036
    Subject: EMAIL=pkinit@addom.samba.example.com,CN=pkinit@addom.samba.example.com,OU=Users,O=SambaSelfTesting,ST=SambaState,C=US
    Subject Public Key Algorithm: RSA
    Algorithm Security Level: Medium (2048 bits)
        Modulus (bits 2048):
            00:b3:a4:e8:bd:c8:4f:6a:71:c6:15:a8:dd:00:d6:61
            74:00:e4:8f:b5:c4:0e:98:d9:51:aa:aa:4f:c7:8c:f9
            6c:37:5c:60:55:da:7c:55:9c:d3:cd:e2:f1:ed:51:39
            25:d5:fa:69:7e:a7:67:9c:a9:61:1b:5c:73:50:d0:6f
            ba:ce:3a:df:fe:ae:95:95:8e:97:ab:c6:bb:6a:c3:60
            0b:ca:c2:9c:31:ff:c6:2f:52:bb:cb:2f:f6:2c:4d:be
            20:e1:16:49:d3:22:36:66:4f:5c:c4:30:12:07:34:8b
            00:4e:5b:51:7d:40:35:81:dc:5c:0e:af:be:78:63:80
            69:67:87:53:97:d0:3f:d7:66:8d:26:8a:0a:24:95:f9
            db:dd:93:0e:48:54:c8:30:e4:77:0d:65:ef:a4:6a:de
            29:91:77:97:40:5c:2e:ed:35:5e:b9:0f:37:ad:d9:70
            76:99:77:45:8c:4a:65:63:13:72:d5:c4:53:37:57:85
            0a:6d:74:30:8c:69:7f:83:f0:7f:f5:67:05:79:80:27
            d4:38:6d:49:2f:8d:2a:97:2e:33:1f:d0:e0:c1:76:1b
            bf:bf:b1:75:8a:c9:b1:3f:3f:f2:4e:c5:b0:68:5e:76
            8a:7e:9c:57:b2:ec:3d:18:83:e2:65:d5:30:5e:b5:f4
            c7
        Exponent (bits 24):
            01:00:01
    Extensions:
        Basic Constraints (not critical):
            Certificate Authority (CA): FALSE
        CRL Distribution points (not critical):
            URI: http://www.samba.example.com/crls/CA-samba.example.com-crl.crl
        Unknown extension 2.16.840.1.113730.1.1 (not critical):
            ASCII: ....
            Hexdump: 030205a0
        Key Usage (not critical):
            Digital signature.
            Non repudiation.
            Key encipherment.
        Unknown extension 2.16.840.1.113730.1.13 (not critical):
            ASCII: .?Smart Card Login Certificate for pkinit@addom.samba.example.com
            Hexdump: 163f536d6172742043617264204c6f67696e20436572746966696361746520666f7220706b696e6974406164646f6d2e73616d62612e6578616d706c652e636f6d
        Subject Key Identifier (not critical):
            3e8165a1e37e18be80fe1593cc2015fd08d4a43d
        Authority Key Identifier (not critical):
            a23e022aa3a74d39b4084d99cc0c7536ea27c33e
        Subject Alternative Name (not critical):
            RFC822Name: pkinit@addom.samba.example.com
            otherName OID: 1.3.6.1.4.1.311.20.2.3
            otherName DER: 0c1e706b696e6974406164646f6d2e73616d62612e6578616d706c652e636f6d
            otherName ASCII: ..pkinit@addom.samba.example.com
        Issuer Alternative Name (not critical):
            RFC822Name: ca-samba.example.com@samba.example.com
        Unknown extension 2.16.840.1.113730.1.4 (not critical):
            ASCII: .>http://www.samba.example.com/crls/CA-samba.example.com-crl.crl
            Hexdump: 163e687474703a2f2f7777772e73616d62612e6578616d706c652e636f6d2f63726c732f43412d73616d62612e6578616d706c652e636f6d2d63726c2e63726c
        Key Purpose (not critical):
            TLS WWW Client.
            1.3.6.1.4.1.311.20.2.2
```

Reproducer:
`make -j20 test TESTS="samba4.blackbox.pkinit" SERVER_LOG_LEVEL="1 kerberos:10" SUBUNIT_FORMATTER=cat`

Branch:
https://git.samba.org/?p=asn/samba.git;a=shortlog;h=refs/heads/asn-pkinit

**Comment by cryptomilk** [comment]
Sorry, wrong log file. Here we go:

[mit_kdc.log](https://github.com/krb5/krb5/files/7881310/mit_kdc.log)

**Comment by cryptomilk** [comment]
The certificates are pre-generated:

https://gitlab.com/samba-redhat/samba/-/tree/master/selftest/manage-ca/CA-samba.example.com

**Comment by greghudson** [comment]
I think you need "pkinit_allow_upn = true" in kdc.conf, alongside pkinit_eku_checking etc.  Otherwise verify_client_san() doesn't retrieve the UPNs from the cert and fails immediately.

But that's not sufficient.  With that change, we do get as far as match_client() with:
* princ->data[0] = "pkinit@addom.samba.example.com"
* princ->realm = "ADDOM.SAMBA.EXAMPLE.COM"
* princ->type = KRB5_NT_ENTERPRISE_PRINCIPAL
* rock->client->princ->data[0] = "pkinit"
* rock->client->realm = "ADDOM.SAMBA.EXAMPLE.COM"

Simple comparison fails, so we call krb5_db_get_principal() on princ, which returns KRB5_KDB_NOENTRY.

**Comment by cryptomilk** [comment]
If I improve the debug message it gets clearer why:

`Jan 18 08:01:25 addc.addom.samba.example.com krb5kdc[25835](info): samba_kdc_fetch: message2entry failed for pkinit\@addom.samba.example.com@ADDOM.SAMBA.EXAMPLE.COM`

It actually adds the realm again.

**Comment by greghudson** [comment]
But I think the realm would also be present if the client made an AS request for the enterprise principal pkinit@addom.samba.example.com.  So (being ignorant of Samba's data model) I wonder if something has to be done during account setup to create the enterprise principal mapping.

**Comment by greghudson** [comment]
I figured it out: we need to pass KRB5_KDB_FLAG_CLIENT in match_client().

That still isn't enough to make the test pass; now instead of a client mismatch error we get a preauth loop error.  This happens because the principal entry has the requires_hwauth flag set, and PKINIT doesn't set the hwauth flag unless a certauth module tells it to.  (And the preauth logic on both sides is too dumb to realize what's going on, so the KDC keeps issuing preauth-required errors and the client keeps trying the same preauthenticated request until the loop count is reached.)

Samba is setting requires_hwauth because the test sets UF_SMARTCARD_REQUIRED.  Requiring hardware auth seems reasonable for this bit, but either Samba or MIT needs to implement smartcard recognition for this to work.

**Comment by cryptomilk** [comment]
Ok, so this means Samba needs to implement a certauth plugin. I can look into that. However it will take a few days as I'm currently adding CI for the bronze bit support. So having runners with MIT KRB5 1.20.

**Comment by cryptomilk** [comment]
After discussion with Sumit and Alexander today. I've changed UF_SMART_CARD_REQUIRED to not set KRB5_KDB_REQUIRES_HW_AUTH, as we want to auth with file based pubkey. So instead we do not fill out key_data for the db entry.

I've implemented a certauth plugin. I would expect that you can put it in the kdc.conf but it looks like it can only be specified in the krb5.conf according to the manpage.

Currently I'm not sure if the plugin has been loaded and I need to add some debug output to find out if it has been loaded or not.

**Comment by greghudson** [comment]
Anything specified in krb5.conf can be specified in kdc.conf and vice versa; the difference is that kdc.conf is only read (and merged in) by KDB-using programs like krb5kdc, kadmind, and kdb5_util.  So you can register a certauth plugin module in kdc.conf.  This is discussed at the top of kdc_conf.rst, although it could be more explicit.

Is there a reason to implement a certauth module if Samba isn't going to require hwauth?

**Comment by cryptomilk** [comment]
> Is there a reason to implement a certauth module if Samba isn't going to require hwauth?

As always with PACs, we want to compare the objectSIDs instead of names. So Samba has a function for that to lookup the certificate principal and compare the sids with the passed in entry:

https://gitlab.com/samba-team/samba/-/blob/master/source4/kdc/db-glue.c#L2572

So I think in order to do that we want a certauth plugin or am I wrong?

**Comment by cryptomilk** [comment]
Is the certauth plugin only loaded if I require hwauth? Or it the certauth plugin loaded whenever pkinit is used?

**Comment by greghudson** [comment]
> As always with PACs, we want to compare the objectSIDs instead of names.

You would need a certauth module for this.  But are there really cases where two principals with different canonical names have the same objectSID or vice versa?

certauth modules are loaded regardless of whether you require hwauth.  There is a trace log message if modules fail to load, so setting a trace logging output file for the krb5kdc process might shed some light on things.  (A lot of the more important PKINIT debugging messages were also converted to trace logs recently.)

**Comment by cryptomilk** [comment]
```diff
 src/lib/krb5/krb/plugin.c | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/src/lib/krb5/krb/plugin.c b/src/lib/krb5/krb/plugin.c
index 3bb7a38d44..819835c13c 100644
--- a/src/lib/krb5/krb/plugin.c
+++ b/src/lib/krb5/krb/plugin.c
@@ -362,6 +362,8 @@ load_if_needed(krb5_context context, struct plugin_mapping *map,
     if (asprintf(&symname, "%s_%s_initvt", iname, map->modname) < 0)
         return;
 
+    com_err("", 0, "XXXXXX Try to bind symbol %s\n", symname);
+
     ret = krb5int_open_plugin(map->dyn_path, &handle, &context->err);
     if (ret) {
         TRACE_PLUGIN_LOAD_FAIL(context, map->modname, ret);
@@ -374,6 +376,8 @@ load_if_needed(krb5_context context, struct plugin_mapping *map,
         goto err;
     }
 
+    com_err("", 0, "XXXXXX Successfuly bound symbol %s\n", symname);
+
     free(symname);
     map->dyn_handle = handle;
     map->module = (krb5_plugin_initvt_fn)initvt_fn;
```

I've added some debug messages to the plugin loading code. However I don't see that the kdc tries to load the certauth plugin:

```
st/ad_dc/logs/mit_kdc.log
1:Jan 20 07:12:54 addc.addom.samba.example.com krb5kdc[10229](info): XXXXXX Try to bind symbol kdcpreauth_pkinit_initvt
3:Jan 20 07:12:54 addc.addom.samba.example.com krb5kdc[10229](info): XXXXXX Successfuly bound symbol kdcpreauth_pkinit_initvt
5:Jan 20 07:12:54 addc.addom.samba.example.com krb5kdc[10229](info): XXXXXX Try to bind symbol kdcpreauth_otp_initvt
7:Jan 20 07:12:54 addc.addom.samba.example.com krb5kdc[10229](info): XXXXXX Successfuly bound symbol kdcpreauth_otp_initvt
9:Jan 20 07:12:54 addc.addom.samba.example.com krb5kdc[10229](info): XXXXXX Try to bind symbol kdcpreauth_spake_initvt
11:Jan 20 07:12:54 addc.addom.samba.example.com krb5kdc[10229](info): XXXXXX Successfuly bound symbol kdcpreauth_spake_initvt
```

**Comment by greghudson** [comment]
`[plugins]`, not `[plugin]`, in mitkdc.conf.

I also noticed that the test is now failing when the client tries to verify the KDC certificate.  From the trace output, it doesn't look like the KDC cert contains a PKINIT SAN:

    [4956] 1642695517.397469: PKINIT client found 2 SANs (0 princs, 0 UPNs, 0 DNS names) in certificate /C=US/ST=SambaState/O=SambaSelfTesting/OU=Domain Controllers/CN=addc.addom.samba.example.com/emailAddress=ca-samba.example.com@samba.example.com

so we need a `pkinit_kdc_hostname = addc.addom.samba.example.com` setting in krb5.conf to authenticate using the CN.

**Comment by cryptomilk** [comment]
Thanks for the pointers. I've fixed `[plugins]` and added `pkinit_kdc_hostname = addc.addom.samba.example.com`. The test still fails :disappointed: 

I've added tracing support now. As soon as you set the kerberos debug level to 10 or higher, e.g.

`make -j20 testenv SELFTEST_TESTENV="ad_dc:local" SERVER_LOG_LEVEL="1 kerberos:10"`

we will write a trace file now. It will end up here: `st/ad_dc/logs/mit_kdc_trace.log`

**Comment by cryptomilk** [comment]
The samba certauth plugin returns 0 for `authorize()`.

**Comment by cryptomilk** [comment]
I've started to work on migrating the test again and one test which we expect to fail is actually succeeding:

`kinit --request-pac -r 1h -X X509_user_identity=FILE:./st/ad_dc/pkinit/USER-pkinit@addom.samba.example.com-cert.pem,./st/ad_dc/pkinit/USER-pkinit@addom.samba.example.com-private-key.pem addc@ADDOM.SAMBA.EXAMPLE.COM`

We request a ticket for addc@ADDOM.SAMBA.EXAMPLE.COM (the DC account) with the certificate of pkinit@ADDOM.SAMBA.EXAMPLE.COM and it succeeds.

**Comment by cryptomilk** [comment]
`37:Jan 24 14:36:43 addc.addom.samba.example.com krb5kdc[20756](info): samba_kdb_certauth_authorize: XXX mit_samba_check_pkinit_ms_upn_match - cert: addc@ADDOM.SAMBA.EXAMPLE.COM, db: ADDC$@ADDOM.SAMBA.EXAMPLE.COM`

Shouldn't the cert princ passed to the certauth plugin be pkinit@ADDOM.SAMBA.EXAMPLE.COM

**Comment by greghudson** [comment]
That parameter is named `princ`, not `cert_princ`, and is the requested client princ.  The whole point of the method is to decide whether the cert (which you get as a DER-encoded byte string) is authorized to authenticate as princ.

**Comment by greghudson** [comment]
I finished up the test case (which involved some ground work) and gave the commits proper messages.

**Pull request merged**
