### PR TITLE
Fix segfault on NULL key_data

### PR DESCRIPTION
**Pull request by mrogers950**
Fail gracefully in case "krbprincipalkey" cannot be read from LDAP.

### CODE REVIEW

**Comment by greghudson** [comment]
For a list defined by a pointer and count, if you want to check whether the list contains at least one member, it's always more correct to check the count than the pointer.  In this case, check n_key_data.

Also, I don't think this test is sufficient; there is a later unconditional use of key_data[0].  We should probably just return an error (perhaps KRB5_KDB_NOMASTERKEY) if there is no key data in K/M.

**Comment by mrogers950** [comment]
Thanks, revision pushed.

**Comment by greghudson** [comment]
The new commit introduces a memory leak when the conditional is true.

**Comment by mrogers950** [comment]
Fixed.

**Comment by greghudson** [comment]
The code change looks okay now.  Can you try to improve the commit message?  Neither the summary nor the explanatory sentence mention master keys at all, and a K/M entry could contain no key data with any KDB module, not just with LDAP.

**Comment by greghudson** [comment]
Oh, also, I found a way to easily reproduce this bug:

    $ kadmin.local purgekeys -all K/M
    $ kadmin.local getprinc user
    Segmentation fault (core dumped)

(It doesn't really matter what the second command is.)  Can you add a regression test to the end of t_mkey.py?

**Comment by mrogers950** [comment]
Thanks, I've updated the commit message and added the t_mkey.py test.

**Comment by greghudson** [comment]
Pushed to master as 83494605b2dd594ab33f9b3cfa5abc82cf0f9e92 f2286a6493c7aab267cf0d9cca680edaf2968707 with minor wording and spacing changes.  (Remember that we use two spaces after sentence-ending periods.)

**Pull request closed without merging**
