### PR TITLE
Visual Studio 2015 build fixes

### PR DESCRIPTION
**Pull request by tsondergaard**
Necessary but insufficient changes to build krb5 on Windows with VS2015. I am submitting this pull request to see if there is interest before pursuing the remaining build issues.

### CODE REVIEW

**Comment by kaduk** [comment]
I believe there is interest in maintaining the ability to build krb5 with current MSVC toolchains, yes.

I am curious what your build environment looks like aside from VS2015, though -- what OS version, where are you getting perl and the unix utilities, what SDK version, etc.

Also, if it's easy, it would be nice to see what the errors look like that these patches fix, though I know it can sometimes be a hassle to get useful build logs, so don't worry about it if it's annoying.

**Comment by tsondergaard** [comment]
We have used krb5-1.11.4 successfully on Windows for a while. I have used both VS2010 and VS2013 with msys tools to build it. I have a very small tool to configure how we build some our dependencies on Windows - it is inspired by rpm .spec files, and it shows how we build krb5 on Windows. I hope it answers your questions. More changes are needed to build with VS2015 and I made this pull request to see if you would accept them.

    # -*-ruby-*-
    class Krb5BuildSpec < BuildSpec
    
      def initialize(build_root, install_prefix_base)
        super
        @name = "krb5"
        @version = "1.11.4"
    
        @build_root_project = File.join(build_root, @name)
        @install_prefix = File.join(@install_prefix_base, @name)
        ENV['KRB_INSTALL_DIR'] = @install_prefix
      end
    
      def extract_source
        cd @build_root
        rm_rf @build_root_project
        rsystem "git clone git://github.com/krb5/krb5.git"
        cd @name
        rsystem "git checkout #{@name}-#{@version}-final"
    
        if (ENV['VisualStudioVersion'] == "12.0")
          patch_file("src/windows/leash/Makefile.in") do
            |s|
            # VS2013/MSDK 8.0 only has static atls.lib.
            # Note that as of VS2013 the MBCS version
            # of MFC is distributed separately.
            # See http://www.microsoft.com/en-us/download/details.aspx?id=40770
            # The VS2013 MBCS version of MFC is known as MFC120(D).LIB
            s.gsub(/atl\.lib/, "atls.lib").
              gsub(/MFC100/, "MFC120")
          end
        end
        patch_file("src/Makefile.in") do
          |s|
          # Looks like plain mistakes to me. Windows releases
          # are not made that often
          s.gsub(/^.*copy\s+windows\\kfwlogon\\.*.pdb.*$/, "\techo patched by krb5.mispec").
            gsub(/^.*copy\s+util\\windows\\.*OUTPRE.*.lib.*$/, "\techo patched by krb5.mispec")
        end
      end
    
      def build
        cd @build_root_project
        rsystem "git clean -dxf"
        cd "src"
    
        ENV['CPU']="i386"
        cygwin_path = "C:/cygwin/bin"
        raise "Cygwin required at '#{cygwin_path}'" if !File.directory?(cygwin_path)
        html_help_path = "C:/Program Files (x86)/HTML Help Workshop"
        raise "html help required at '#{html_help_path}'" if !File.directory?(html_help_path)
        ENV['PATH'] = ENV['PATH'] + ";#{to_native(cygwin_path)};#{to_native(html_help_path)}"
    
        # Note: Leash will fail to build if Multibyte version of MSV for
        # Visual Studio 2013 is not installed (it is a separate download)
        rsystem "nmake -f Makefile.in prep-windows"
        rsystem "nmake NODEBUG=1 DEBUG_SYMBOL=1"
      end
    
      def install
        cd @build_root_project
        rm_rf @install_prefix
        mkdir @install_prefix
        cd "src"
        rsystem "nmake install NODEBUG=1 DEBUG_SYMBOL=1"
        rm Dir.glob(File.join(@install_prefix, "bin/*.pdb"))
      end
    
      def symbol_files
        [ @build_root_project ]
      end
    
    end
    
    builder.build(Krb5BuildSpec)

**Comment by tsondergaard** [comment]
This is the compile error fixed by 9d678f9 VS2015 build fix: Define HAVE_VSNPRINTF if VS2015 or newer:
```
cl    -I.\..\..\include -I.\..\..\include\krb5 -I..\..\windows\include -DWSHELPER=1 -DKRB5_DNS_LOOKUP=1 -DWIN32_LEAN_AND_MEAN -DKRB5_DEPRECATED=1 -DKRB5_PRIVATE -D_CRT_SECURE_NO_DEPRECATE -DUSE_LEASH=1 -D_USE_32BIT_TIME_T /Os /MD /Zi -nologo /EHsc /W3 -Fdobj\i386\rel\\ -FD  -Foobj\i386\rel\\ -c ...
threads.c
D:\src\krb5\src\include\k5-platform.h(925): error C2375: 'vsnprintf': redefinition; different linkage
C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt\stdio.h(1426): note: see declaration of 'vsnprintf'
D:\src\krb5\src\include\k5-platform.h(940): error C2375: 'snprintf': redefinition; different linkage
C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt\stdio.h(1932): note: see declaration of 'snprintf'
```

This is the build error fixed by dc3a285 VS2015 build fix: VS2015 math.h defines OVERFLOW:
```
deltat.c(191): error C2059: syntax error: 'constant'
x-deltat.y(225): error C2065: 'tok_WS': undeclared identifier
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2'
```

I don't have a build log around for the error fixed by b17f2a5 VS2015 build fix: Need space between string literal and macro.

**Comment by greghudson** [comment]
Pushed to master as a14739f2a2acac30a8aba6f8e9f8f5a34bd38d6e

**Comment by tsondergaard** [comment]
@greghudson , only one commit out of the three has been picked?

**Pull request closed without merging**
