### PR TITLE
Deindent krb5_string_to_keysalts

### PR DESCRIPTION
**Pull request by tlyu**
Remove a level of indentation for the list-appending part of the
krb5_string_to_keysalts() loop body by consolidating the strtok_r()
calls into the controlling expreession of the loop.

### CODE REVIEW

**Comment by greghudson** [comment]
Seems okay.  I think a for loop could also work to eliminate the need for p, but I don't have a strong preference.

    for (ksp = strtok_r(copy, tseps, &tlasts); ksp != NULL;
          ksp = strtok_r(NULL, tsteps, &tlasts)) {

**Comment by tlyu** [comment]
I prefer to avoid splitting the clauses of a for-statement across multiple lines.

**Comment by tlyu** [comment]
Pushed as f2f95f490e405c6e2889a0630915a9e729b6906c

**Comment by tlyu** [comment]
Actually pushed as e110ce6ed19f5349e304e826e6b8066312c6c15c because I forgot to push it before closing this pull request and then other commits landed after.

**Pull request closed without merging**
