### PR TITLE
RBCD KDC fixups

### PR DESCRIPTION
**Pull request by iboukris**
As discussed, I tested each commit with the broken client and it gets an error.

### CODE REVIEW

**Comment by greghudson** [comment]
local_tgs leaks in the second patch, in test_get_principal().

**Comment by iboukris** [comment]
Pushed a fix.

**Comment by greghudson** [comment]
Minor edits.  I changed KRB_AP_ERR_NOT_US to KRB5_KDB_NOENTRY.  The former is a protocol  code (KRB5KRB_AP_ERR_NOT_US would be the corresponding com_err code), and KRB5_KDB_NOENTRY more accurately reflects what a regular KDB would return for a non-local principal lookup.

**Comment by iboukris** [comment]
Looks good thanks, btw Windows would return WRONG_REALM (with no hint).

**Pull request merged**
