### PR TITLE
Rename KDB authdata param server_princ to request_server

### PR DESCRIPTION
**Pull request by iboukris**
to distinguish it from PAC server.

### CODE REVIEW

**Comment by greghudson** [comment]
I'm not sure I like this change.  The existing names distinguish between principal names and KDB entries, and server_princ is documented properly.  I don't see any misleading suggestion in the existing names that server_princ corresponds to header_server.

**Comment by iboukris** [comment]
Ok, it confused me that server_princ and server can be different entities.

**Comment by greghudson** [comment]
> Ok, it confused me that server_princ and server can be different entities.

In the referral case, or in other cases?  I'm not sure how this relates to the PAC server, which as far as I know is header_server.

**Comment by iboukris** [comment]
My confusion was about get_authdata_info() that actually takes a server_key and that server_princ (used for delegation-info blob), and then there is the referral case. But the doc is ok.

**Comment by greghudson** [comment]
The change at kdb.h:1294 threw me off, because it changes the comment for sign_authdata.  Is that an error?

**Comment by iboukris** [comment]
It's the same argument to both functions, so I changed both

**Pull request closed without merging**
