### PR TITLE
client referral: return correct client principal in case of a wrong realm

### PR DESCRIPTION
**Pull request by abbra**
prepare_error_as_req() gets protocol error code but compares it with
table code and misses to add proper client principal as returned by the
DAL driver.

Rework the code to avoid errcode comparison within prepare_error_as_req().

### CODE REVIEW

**Comment by greghudson** [comment]
Please review the top two commits at https://github.com/greghudson/krb5/commits/client_referral as a counterproposal.

I'm no longer sure that I like the idea of changing the code to pass an unconditional client princ to prepare_error_as(); it adds too much complexity to finish_as_req() which is in dire need of refactoring (a perennial problem for the KDC code).  It might be better to push more responsibility down into prepare_error_as(), perhaps passing it the state pointer instead of a half-dozen fields of it.  I will defer that work to a later time.

**Comment by abbra** [comment]
I'm fine with your patch If you want to do refactoring of prepare_error_as() later.

**Comment by tlyu** [comment]
@greghudson your patches look OK to me.

**Comment by greghudson** [comment]
Pushed to master as 4e036ef4127a9b09d1a567472da1df24c55cdb89 1e4a0394d0085e48d732ab318f9cbe08e9359587

**Pull request closed without merging**
