### PR TITLE
Add indentation checking to cstyle-file.py

### PR DESCRIPTION
**Pull request by greghudson**
For each file we check in cstyle-file.py, try to use emacs to
batch-reindent a copy of the file, and compare the resulting lines to
the input to detect indentation errors.

[PR commentary only:] Using emacs for this checking is kind of slow, because the emacs startup has to happen for every changed .c or .h file.  The layering of cstyle.py and cstyle-file.py doesn't make it easy to do multiple files in one emacs invocation.  It's still a lot faster to have a slow tool checking for these errors than to have a human notice it and give PR feedback.

We could alternatively use clang-format or indent, but I think we would have to change our coding practices to strictly conform to a configurable style in one tool or the other, or else they would generate a lot of false positives.  clang-format is also a bit of a moving target, and doesn't make it easy to write one style file for multiple versions.

### CODE REVIEW

**Comment by frozencemetery** [comment]
Would it perhaps be faster to start an emacs server (`emacs --daemon`) and run emacsclient to connect to it for each file?  Naively it looks like it should be possible with --eval.

**Comment by tlyu** [comment]
That might not work well for those of us who keep emacs running all the time with an emacs server. Connecting to the currently running emacs could contaminate what should be a standardized process with our personal configuration quirks. Also I'm not sure if having multiple emacs server processes running simultaneously is a good idea.

**Comment by tlyu** [comment]
I tested this change against a known-nonconforming file (via make reindent) and it seems to work as expected. I'm ok with this change as is, unless we want to pursue @frozencemetery's suggestion.

**Comment by frozencemetery** [comment]
Interacting with existing emacs daemons is a good point.  I see flags for emacsclient to select which emacs daemon to connect to, but I don't see a way to start multiple emacs daemons.

I am therefore okay with this approach as written.

**Pull request merged**
