### PR TITLE
Allow aliases in U2U 2nd ticket matching

### PR DESCRIPTION
**Pull request by iboukris**
As mentioned in #1106, see bug below. Note that I don't have a way to test it, i'll ask Dario:
https://bugzilla.redhat.com/show_bug.cgi?id=1836630

### CODE REVIEW

**Comment by iboukris** [comment]
Got feedback from Dario, it looks good, updated the PR.

**Comment by greghudson** [comment]
Just checking if I follow correctly on is_client_alias():

* Originally it took a DB entry (containing the canonical principal name) and a principal name to be looked up.
* It was changed to take two principal names (one canonical, the other to be looked up) because the proposed is_local_principal() change in PR #1106 needed to use tgs_server (a principal name) as the canonical principal to compare against.
* Since we expect to stop using tgs_server, we can go back to taking a DB entry.

**Comment by iboukris** [comment]
Yep exactly, i like the db entry better because the canon is implied.

**Comment by greghudson** [comment]
In the tests, does the "Try u2u against the client user" test anything specific to this commit, or is it leftover copy-paste?  (The klist invocation seems like leftover, and in fact I'm not sure why it's there in the existing tests.)

**Comment by iboukris** [comment]
Yeah, mostly copy-paste.

**Pull request merged**
