### PR TITLE
Suggestion for code style fix.

### PR DESCRIPTION
**Pull request by fmmedeiros**
Adding brackets to show explicitly that the else of line 185 belongs to the if statement of line 183, and the first if starting at line 181.

### CODE REVIEW

**Comment by kaduk** [comment]
Note that this part of the tree is bundled from the external libverto project and will periodically get re-imported from upstream libverto as we have a need for any updates/fixes from there.
We do make some additional patches on top of upstream, and I agree that your proposal is better style, but it is unclear whether the benefit outweighs the risk of a harder import in the future.

**Comment by fmmedeiros** [comment]
Ok, Thanks!

**Comment by frozencemetery** [comment]
@fmmedeiros Should you (or anyone else) wish to contribute to libverto, I maintain the repository on github at [latchset/libverto](https://github.com/latchset/libverto/).

**Comment by greghudson** [comment]
I believe this particular change was to libev, not libverto.

**Pull request closed without merging**
