### PR TITLE
Update copyright years to 2017

### PR DESCRIPTION
**Pull request by mmattioli**
Update copyright years to 2017 where appropriate given the impending new year

### CODE REVIEW

**Comment by greghudson** [comment]
Can we hit src/prototype/prototype.[ch] in the same commit this time around?  I think we forgot to update those until later in 2016.

**Comment by mmattioli** [comment]
@greghudson just adjusted

**Comment by greghudson** [comment]
Looking at other copyright updates we made in 2016, we also want to hit src/windows/version.rc.  I think that's it; sorry to give this feedback in two separate pieces.

**Comment by mmattioli** [comment]
@greghudson no worries, just updated

**Pull request merged**
