### PR TITLE
Remove a bunch of static variables in the kadmin client and server libraries

### PR DESCRIPTION
**Pull request by simo5**
Also fixes a couple memleaks in the client, and removes a to of duplicated code in the server.

This patchset depends (and incorporates until pushed) on the one in PR #375

### CODE REVIEW

**Comment by simo5** [comment]
Rebased and squashed the commits.
Note: this PR depends on #375 so it includes all its commits until it is pushed, only the last 2 commits are actual code changes belonging to this PR

**Comment by greghudson** [comment]
The recent CVE commits changed the server stubs, so this will need to be rebased.  Also, setup_stub_srv() should return an error if princ_str is non-null but princ is null, as it means the client unexpectedly passed a null principal name.

**Comment by simo5** [comment]
Ok rebased to fix the conflicts

**Comment by greghudson** [comment]
Our practice is to put output parameters at the end; this PR seems to add a whole bunch to the beginning of RPC stub functions.

**Comment by greghudson** [comment]
Also, the SERVER typedef seems weirdly incongruous.  Is there really a problem with continuing to use struct svc_req?

**Comment by simo5** [comment]
I think I used the SERVER typedef to avoid blowing through the 80 col limit mostly.

**Comment by greghudson** [comment]
From voice discussion:

* The SERVER typedef should be undone; it's deceptive because it's a server request object, not a server handle.

* Simo should leave alone the output parameter positioning and stub function renaming for now; Tom and I will figure out whether we want that to change.

**Comment by simo5** [comment]
Rebased on #375 and renamed back SERVER to struct svc_req as requested.

**Comment by greghudson** [comment]
I took a look at the rpcgen state of the art for thread-safe RPC stubs.  If you run rpcgen -M on a .x file, you get client stubs which look like:

```
enum clnt_stat
iprop_get_updates_1(kdb_last_t *argp, kdb_incr_result_t *clnt_res, CLIENT *clnt)
{
        return (clnt_call(clnt, IPROP_GET_UPDATES,
                (xdrproc_t) xdr_kdb_last_t, (caddr_t) argp,
                (xdrproc_t) xdr_kdb_incr_result_t, (caddr_t) clnt_res,
                TIMEOUT));
}
```

and server stubs which look like:

```
bool_t
iprop_get_updates_1_svc(kdb_last_t *argp, kdb_incr_result_t *result, struct svc_req *rqstp)
{
        bool_t retval;

        /*
         * insert server code here
         */

        return retval;
}
```

Perhaps we should follow this convention rather than creating our own?  bool_t and enum clnt_stat are existing RPC types.

**Comment by simo5** [comment]
So your request would be to return a bool_t for the server and invert arg, and result arguments for both client and server calls ?
Or something else ?

**Comment by greghudson** [comment]
In addition to what you said:

* The client stubs should return the result of clnt_call() rather than setting a code in the result structure and returning void.
* The client and server stubs should go back to the names they have in master.

For the boolean return value of the server stubs, it looks like false means not to send a reply, just like returning NULL would mean on master.  I think for our existing stubs that means we always return true, since we never return NULL at present.

**Comment by simo5** [comment]
Do you want to change all return structures to not include a status code, or should we just set it as well as return it from the client stubs ?
Changing all the xx_ret structures is a bigger change than what we have in this PR currently.

**Comment by simo5** [comment]
I think I have addressed the requests (clarified on IRC) with this new patchset.

**Comment by greghudson** [comment]
Pushed to master as 0937ccdd4e97c474bc1b79e059f1301ae6c851ea 01d2bd6ab3f39163f6185ac4c69f6f87535212b4.

**Pull request closed without merging**
