### PR TITLE
Add internal SHA-256 interface

### PR DESCRIPTION
**Pull request by greghudson**
Add a simple private libk5crypto interface for computing SHA-256
hashes.

### CODE REVIEW

**Comment by tlyu** [comment]
This looks mostly OK to me. There's no test coverage for the new interface, but we do have testing for the underlying interfaces (init/update/fini) that it uses. I don't have a strong opinion on whether to add a test specifically for the new interface. What do you think?

**Comment by greghudson** [comment]
I think it's okay to leave that specific interface untested for now.  (Obviously it will get some coverage testing when the rcache code is changed to use it, but that won't test for correct SHA-256 results.)  This code will also be affected by the aes-sha2 enctype work (see https://github.com/greghudson/krb5/commit/aba206c654b6b4292ec7d9866ff2cad1b295cda8).  We could conceivably, in that commit, put t_sha2.c in crypto_tests rather than builtin/sha2 and test the k5_sha256() interface.

**Comment by tlyu** [comment]
That's tempting, but we probably should avoid unrolling the "one million a's" test if we're going to do that.

**Comment by greghudson** [comment]
Does the test program in https://github.com/greghudson/krb5/commit/eea0bd75432254317af035d701067db804d23bbe look reasonable?  It uses the hash_provider interface with a thousand IOVs for the "one million a's" test, which results in a thousand k5_sha256_update() calls in the builtin module.

**Pull request merged**
