### PR TITLE
finish realm should free keys with 0 length too

### PR DESCRIPTION
**Pull request by Sashan**
Same patch has been sent to [krbdev](http://mailman.mit.edu/pipermail/krbdev/2018-February/012900.html) few days ago from my Alexandr.Nedvedicky company email

### CODE REVIEW

**Comment by greghudson** [comment]
It looks like this trivial bug happens when the test suite uses the test KDB module, which returns a zeroed master key when asked for one.  Looking at the code which frees the realm master key, I'd like to see that whole conditional block to free realm_mkey replaced with:

    zapfree(rdp->realm_mkey.contents, rdp->realm_mkey.length);

**Comment by Sashan** [comment]
OK. the most recent version uses `zaprfree()`

**Comment by greghudson** [comment]
zapfree() checks the pointer for null, so we can just call it without the conditional.

**Comment by Sashan** [comment]
> `zapfree()` checks the pointer for null, so we can just call it without the conditional.

thanks, I've just killed the `if ()`

**Pull request merged**
